title: Tyrah Cobb-Davis (she/her) # your name (or website title) here
logo: "/images/tyrahheadshot.png?raw=true"  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Master's Student | Geography and Environmental Systems
  <br><br>
  University of Maryland, Baltimore County  
  <br><br>
  <a href="https://www.linkedin.com/in//tyrah-cobb-davis-60007717b/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal

